apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: php-plantilla
  annotations:
    description: "Plantilla para desplegar un deployment de php"
    iconClass: "icon-php"
    tags: "database,php"
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: app1
    name: app1
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: app1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: app1
      spec:
        containers:
        - image: default-route-openshift-image-registry.apps.sandbox-m3.1530.p1.openshiftapps.com/josedom24-dev/app1:1
          imagePullPolicy: Never
          name: app1
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
            - app1
            from:
              kind: ImageStreamTag
              name: app1:1
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: app1
    name: app1
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentconfig: app1
    type: ClusterIP
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: app1
    name: app1
  spec:
    tags:
    - name: "latest"
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: app1
    name: app1
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: app1:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/josedom24/osv4_php
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:7.3-ubi7
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: app1
    name: app1
  spec:
    host: app1-josedom24-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: app1
      weight: 100
    wildcardPolicy: None
