apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: citas
    type: database
spec:
  selector:
    app: citas
    type: database
  ports:
  - port: 3306
    targetPort: db-port
  type: ClusterIP