apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: php-plantilla
metadata:
  name: php-plantilla
  annotations:
    openshift.io/display-name: Mi plantilla de PHP
    description: "Plantilla para desplegar un deployment de php"
    iconClass: "icon-php"
    tags: "php"
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: ${NOMBRE}
    name: ${NOMBRE}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: ${NOMBRE}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: ${NOMBRE}
      spec:
        containers:
        - image: ' '
          name: ${NOMBRE}
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - ${NOMBRE}
          from:
            kind: ImageStreamTag
            name: ${NOMBRE}:latest
        type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NOMBRE}
    name: ${NOMBRE}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${NOMBRE}
    type: ClusterIP
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: ${NOMBRE}
    name: ${NOMBRE}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: ${NOMBRE}
    name: ${NOMBRE}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NOMBRE}:latest
    source:
      git:
        uri: ${REPOSITORIO_GIT}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:${PHP_VERSION}
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NOMBRE}
    name: ${NOMBRE}
  spec:
    to:
      kind: Service
      name: ${NOMBRE}

parameters:
- description: El nombre asignado a la aplicaci贸n y a los recursos creados.
  displayName: Nombre
  name: NOMBRE
  required: true
  value: app-php
- description: Versi贸n de PHP
  displayName: Versi贸n de php
  name: PHP_VERSION
  required: true
  value: latest
- description: URL del repsositorio GItHub donde se encuentra la aplicaci贸n
  displayName: URL del repositorio Git
  name: REPOSITORIO_GIT
  required: true
  value: https://github.com/josedom24/osv4_php
- description: Token para webhook de GitHub   
  displayName: GitHub Webhook Token
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET