apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: test-web2
  labels:
    app: test-web
spec:
  strategy:
    type: Rolling
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - name: test-web
          image: josedom24/test_web@sha256:99db6f7fdcd6aa338d80b5cd926dff8bae50062c49f82c79a3d67d048efb13a4
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - contenedor-test-web
        from:
          kind: ImageStreamTag
          name: test-web:v1
      