apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      service: web
  template:
    metadata:
      labels:
        app: nginx
        service: web
    spec:
      containers:
        - image: bitnami/nginx
          name: contenedor-nginx
         