apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: citasweb
    sandbox: learn-kubernetes
    sandbox-learn-kubernetes: citasweb
  name: citasweb
spec:
  port:
    targetPort: 5000-tcp
  to:
    kind: Service
    name: citasweb